# name: Build BC App

# on:
#   push:
#     branches:
#       - master
#       - main

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Show project files
#         run: dir

name: Build BC App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install BcContainerHelper
        shell: powershell
        run: |
          Install-Module BcContainerHelper -Force -AllowClobber

      - name: Create BC Container
        shell: powershell
        run: |
          $artifactUrl = Get-BCArtifactUrl -type Sandbox -country us -select Latest

          New-BcContainer `
            -accept_eula `
            -containerName bccontainer `
            -artifactUrl $artifactUrl `
            -auth UserPassword `
            -credential (New-Object pscredential 'admin',(ConvertTo-SecureString 'P@ssword1' -AsPlainText -Force)) `
            -updateHosts
            -additionalParameters @("--volume $($env:GITHUB_WORKSPACE):c:\src")

      # - name: Compile AL Project
      #   shell: powershell
      #   run: |
      #     Compile-AppInBCContainer `
      #       -containerName bccontainer `
      #       -appProjectFolder $env:GITHUB_WORKSPACE `
      #       -outputFolder $env:GITHUB_WORKSPACE\output

      - name: Compile AL Project
        shell: powershell
        run: |
          Compile-AppInBCContainer `
          -containerName bccontainer `
          -appProjectFolder "c:\src"
          -credential (New-Object pscredential 'admin',(ConvertTo-SecureString 'P@ssword1' -AsPlainText -Force))

      - name: Create Output Folder
        shell: powershell
        run: |
          -Credential (New-Object PSCredential 'admin',(ConvertTo-SecureString 'P@ssword1' -AsPlainText -Force))

      - name: Copy App File
        shell: powershell
        run: |
          Copy-Item `
          -Path "C:\ProgramData\BcContainerHelper\Extensions\bccontainer\*.app" `
          -Destination "$env:GITHUB_WORKSPACE\output" -Recurse

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BC-App
          path: output/*.app
